"""
This type stub file was generated by pyright.
"""

from squaternion.squaternion import Axis, Quaternion
from importlib.metadata import version

__author__ = ...
__license__ = ...
__version__ = ...
